site_name: Art. Technology. Life
pages:
    - Home: index.md
    - Blog:
        - 'Заметка 1 (1)': 2018/2018-04-02_01.note.md
        - 'Заметка 2 (2)': 2018/2018-04-02_02.note.md
        - 'Заметка 3 (3)': 2018/2018-04-02_03.note.md
        - 'Клиентоориентированность (4)': 2018/2018-04-03_01_Klientoorientirovannost.md
    - Extras:
        - 'Codefest 2018 notes':
            - 'How to invent (@bobuk)': codefest2018/02.how-to-invent-bobuk.md
