site_name: Art. Technology. Life
pages:
    - Home: index.md
    - Blog:
        - 'note (01)': 2018/2018-04-02_01.note.md
        - 'note (02)': 2018/2018-04-02_02.note.md
        - 'note (03)': 2018/2018-04-02_03.note.md
