site_name: Art. Technology. Life
theme: cinder
pages:
    - Home: index.md
    - Blog:
        - 'Заметка 1 (1)': 2018/2018-04-02_01.note.md
        - 'Заметка 2 (2)': 2018/2018-04-02_02.note.md
        - 'Заметка 3 (3)': 2018/2018-04-02_03.note.md
        - 'Клиентоориентированность (4)': 2018/2018-04-03_01_Klientoorientirovannost.md
        - 'Двигатель прогресса (5)': 2018/2018-04-03_02_Dvigatel_progressa.md
        - 'Парадокс ерунды (6)': 2018/2018-04-05_01_Paradoks_erundy.md
        - 'Инструменты и расходные материалы (7)': 2018/2018-04-06_01_Instrumenty_i_rasxodnye_materialy.md
        - 'Инструменты (8)': 2018/2018-04-14_01_Instrumenty.md
        - 'Против (9)': 2018/2018-05-06_01_protiv.md
        - 'Ценности (10)': 2018/2018-05-08_01_Czennosti.md
        - 'Вы сможете рисовать через 30 дней (11)': 2018/2018-05-12_01_Knigi_o_kotoryx_ya_upominal_na_nabroskax_1.md
        - 'Воспитай в себе обезьяну (12)': 2018/2018-05-18_01_Vospitaj_v_sebe_obezyanu.md
        - 'И тут появился изобретатель (13)': 2018/2018-05-18_02_I_tut_poyavilsya_izobretatel.md
        - 'Рисуй, чтобы победить (14)': 2018/2018-05-18_03_Risuj,_chtoby_pobedit.md
        - 'What can you really draw in 15 seconds? (15)': 2018/2018-05-19_01_What_can_you_really_draw_in_15_seconds.md
        - 'Непонятное искусство (16)': 2018/2018-05-19_02_Neponyatnoe_iskusstvo.md
    - Extras:
        - 'Заметки с Codefest 2018':
            - 'Заметки с Codefest 2018': codefest2018.md
            - 'Что делать, чтобы изобретать': codefest2018/02.how-to-invent-bobuk.md
            - 'Профессиональное выгорание': codefest2018/04.Professionalnoe_vygoranie.md
    - Tags:
        - '#award': by_tag/award.md
        - '#blog': by_tag/blog.md
        - '#life': by_tag/life.md
        - '#like': by_tag/like.md
        - '#music': by_tag/music.md
        - '#punk': by_tag/punk.md
        - '#technology': by_tag/technology.md
        - '#инструменты': by_tag/instrumenty.md
        - '#книгиокоторыхяупоминалнанабросках': by_tag/knigiokotoryxyaupominalnanabroskax.md
        - '#лень': by_tag/len.md
        - '#любопытство': by_tag/lyubopytstvo.md
        - '#мечты': by_tag/mechty.md
        - '#против': by_tag/protiv.md
        - '#работа': by_tag/rabota.md
        - '#ценности': by_tag/cennosti.md
