site_name: Art. Technology. Life
theme: cinder
pages:
    - Home: index.md
    - Blog:
        - 'Заметка 1 (1)': 2018/2018-04-02_01.note.md
        - 'Заметка 2 (2)': 2018/2018-04-02_02.note.md
        - 'Заметка 3 (3)': 2018/2018-04-02_03.note.md
        - 'Клиентоориентированность (4)': 2018/2018-04-03_01_Klientoorientirovannost.md
        - 'Двигатель прогресса (5)': 2018/2018-04-03_02_Dvigatel_progressa.md
        - 'Парадокс ерунды (6)': 2018/2018-04-05_01_Paradoks_erundy.md
        - 'Инструменты и расходные материалы (7)': 2018/2018-04-06_01_Instrumenty_i_rasxodnye_materialy.md
    - Extras:
        - 'Заметки с Codefest 2018':
            - 'Заметки с Codefest 2018': codefest2018.md
            - 'Что делать, чтобы изобретать': codefest2018/02.how-to-invent-bobuk.md
            - 'Профессиональное выгорание': codefest2018/04.Professionalnoe_vygoranie.md
