#!/usr/bin/perl -w
use strict;
use feature qw/say/;

use Set::Scalar;

use Lingua::Translit;

sub transliterate {
	my ($str) = @_;
	my $tr = new Lingua::Translit('GOST 7.79 RUS');
	return map { my $x = $tr->translit($_); $x =~ s/[`']//; $x } @_;
}

sub preview_file {
	my ($file, $out) = @_;
	my ($link) = $file =~ m{^[^/]+(/.*)\.md$};
	open my $in, "<", $file or die "$!";
	print $out "#";
	my $is_title = 1;
	while (my $line = <$in>) {
		chomp $line;
		if ($is_title && $line) {
			my ($title) = $line =~ m/^##\s*(\S.*)$/;
			if ($title) {
				say $out "## [$title]($link)";
				$is_title = 0;
			} else {
				say $out $line;
			}
			next;
		}
		say $out "$line";
		unless ($line eq "" || $line =~ /^[#`_]/) {
			say $out "[Далее]($link/)\n";
			last;
		}
	}
	close $in or warn $!;
}

sub find_all_tags {
	my (@files) = @_;
	my @tags;
	my $tags = Set::Scalar->new;
	for my $f(@files) {
		my $content;
		open my $in, "<", $f or die "$f : $!";
		{
			local $/;
			$content = <$in>;
		}
		close $in;
		my ($tag_str) = $content =~ /`(#[^`]+)`/;
		$tags->insert(split(/\s+/, $tag_str));
	}
	return sort(map {substr($_, 1)} $tags->elements);
}

my $site_name = "Art. Technology. Life";
my $theme = "cinder";
my $subtitle = "![Cubes](/image/00-white-cube.jpg)\n\n*Блог Александра Воронкова*";

my @files = `ls docs/20*/*.md | sort --reverse`;
chomp @files;

open my $index, ">", "docs/index.md" or die $!;
print $index <<"EOL";
# $site_name

$subtitle

## Заметки
EOL

my $max = $#files > 9 ? 9 : $#files;
for my $file(@files[0..$max]) {
	preview_file($file, $index);
}

close $index;


open my $yml, ">", "mkdocs.yml" or die $!;
print $yml <<"EOL";
site_name: $site_name
theme: $theme
pages:
    - Home: index.md
    - Blog:
EOL

my $n = 1;
for my $file(reverse @files) {
	chomp(my $title = `head -n 1 $file`);
	($title) = $title =~ /^## (.*)$/;
	my ($path) = $file =~ m{^docs/(.+)$};
	say $yml "        - '$title ($n)': $path";
	$n++;
}

close $yml;

sub process_misc {
	my ($name) = @_;
	open my $r, "<", "docs/$name.md" or die "$!";
	chomp(my @lines = <$r>);
	close $r or warn "$!";

	my ($title) = $lines[0] =~ m/^# (.*)$/;

	open my $y, ">>", "mkdocs.yml" or die "$!";
	say $y "        - '$title':";
	say $y "            - '$title': $name.md";

	open my $f, ">", "docs/$name.md" or die "$!";
	say $f "# $title";

	`echo "- [$title](/$name/)" >> docs/index.md`;

	my @files = sort(glob("docs/$name/*.md"));
	for my $file(@files) {
		open my $x, "<", $file or die "$file : $!";
		my @l = <$x>;
		close $x or warn "$!";
		my ($t) = $l[0] =~ m/#\s*(.*)\s*$/;
		my ($link) = $file =~ m{^.*/([^/]*)\.md$};
		say $f "- [$t](/$name/$link/)\n";

		say $y "            - '$t': $name/$link.md";
	}
	close $f or warn "$!";
	close $y or warn "$!";
}

sub process_tag {
	my ($tag, $title) = @_;
	my @files_with_tag = qx/grep -Rn '`#' @files | grep '`#$tag\\b' | cut -d: -f 1/;
	chomp(@files_with_tag);

	my ($filename) =  transliterate($tag);
	my $tag_file = "docs/by_tag/" . $filename . ".md";
	open my $f, ">", $tag_file or die "$! : $tag_file";
	if ($title) {
		say $f "# $title";
		say $f "`#$tag`\n";
	} else {
		say $f "# #$tag\n";
	}
	for my $a(@files_with_tag) {
		preview_file($a, $f);
	}
	close $f;

	my ($short_path) = $tag_file =~ m{^docs/(.*)$};
	`echo "        - '#$tag': $short_path" >> mkdocs.yml`;
}

`echo '    - Extras:' >> mkdocs.yml`;
`echo '## Разное' >> docs/index.md`;
process_misc "codefest2018";

`echo '    - Tags:' >> mkdocs.yml`;
my %known_tags = (
	'книгиокоторыхяупоминалнанабросках' => 'Книги, о которых я упоминал на набросках',
);

for my $tag(find_all_tags(@files)) {
	if (exists $known_tags{$tag}) {
		process_tag $tag, $known_tags{$tag};
	} else {
		process_tag $tag;
	}
}
