#!/usr/bin/perl -w
use strict;
use feature qw/say/;

my $site_name = "Art. Technology. Life";
my $subtitle = "![Cubes](/image/00-white-cube.jpg)\n\n*Блог Александра Воронкова*";

my @files = `ls docs/20*/*.md | sort --reverse`;
chomp @files;

open my $index, ">", "docs/index.md" or die $!;
say $index "# $site_name\n";
say $index $subtitle;
say $index "## Заметки";

my $max = $#files > 9 ? 9 : $#files;

for my $file(@files[0..$max]) {
	open my $in, "<", $file or die "$!";
	print $index "#";
	while (my $line = <$in>) {
		chomp $line;
		say $index "$line";
		unless ($line eq "" || $line =~ /^[#`_]/) {
			my ($link) = $file =~ m{^[^/]+(/.*)\.md$};
			say $index "[Далее]($link/)\n";
			last;
		}
	}
	close $in or warn $!;
}

close $index;


open my $yml, ">", "mkdocs.yml" or die $!;
say $yml "site_name: $site_name";
say $yml "pages:";
say $yml "    - Home: index.md";
say $yml "    - Blog:";

my $n = 1;
for my $file(reverse @files) {
	chomp(my $title = `head -n 1 $file`);
	($title) = $title =~ /^## (.*)$/;
	my ($path) = $file =~ m{^docs/(.+)$};
	say $yml "        - '$title ($n)': $path";
	$n++;
}

close $yml;

# -s "mkdocs.yml.tail" and qx/cat mkdocs.yml.tail >> mkdocs.yml/;

sub process_misc {
	my ($name) = @_;
	open my $r, "<", "docs/$name.md" or die "$!";
	chomp(my @lines = <$r>);
	close $r or warn "$!";

	my ($title) = $lines[0] =~ m/^# (.*)$/;

	open my $y, ">>", "mkdocs.yml" or die "$!";
	say $y "        - '$title':";
	say $y "            - '$title': $name.md";

	open my $f, ">", "docs/$name.md" or die "$!";
	say $f "# $title";

	`echo "- [$title](/$name/)" >> docs/index.md`;

	my @files = sort(glob("docs/$name/*.md"));
	for my $file(@files) {
		open my $x, "<", $file or die "$file : $!";
		my @l = <$x>;
		close $x or warn "$!";
		my ($t) = $l[0] =~ m/#\s*(.*)\s*$/;
		my ($link) = $file =~ m{^.*/([^/]*)\.md$};
		say $f "- [$t](/$name/$link/)\n";

		say $y "            - '$t': $name/$link.md";
	}
	close $f or warn "$!";
	close $y or warn "$!";
}

`echo '    - Extras:' >> mkdocs.yml`;
`echo '## Разное' >> docs/index.md`;
process_misc "codefest2018";
